In [1]:
# -*- coding: utf-8 -*-
import argparse
import os
import string
import sys
os.chdir('/home/hyeryung_son/mucoco')
from itertools import repeat
import torch.multiprocessing as mp
from typing import List

import numpy as np
import pandas as pd
import torch
import transformers
from datasets import Dataset
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoModelForMaskedLM, AutoTokenizer, AutoConfig

from new_module.utils.robertacustom import RobertaCustomForSequenceClassification
from new_module.locate.new_locate_utils import *
import new_module.losses as lossbuilder

import logging
import os
from typing import List
from tqdm import tqdm

import torch
import torch.nn.functional as F
import transformers

In [2]:
## setup for prototyping
logging.basicConfig(level=logging.DEBUG, format="%(message)s")
logger = logging.getLogger(__name__)
logger.setLevel(os.environ.get("LOGGING_LEVEL", logging.DEBUG))

config={#'model_paths':['gpt2-large','/shared/s3/lab07/hyeryung/loc_edit/roberta-base-jigsaw-toxicity-classifier-energy-training/step_600_best_checkpoint'],
        # 'tokenizer_paths':['gpt2-large','/shared/s3/lab07/hyeryung/loc_edit/roberta-base-jigsaw-toxicity-classifier-energy-training/step_600_best_checkpoint'],
        'model_paths':['gpt2-large','models/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/checkpoint_best'],
        'tokenizer_paths':['gpt2-large','models/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/checkpoint_best'],
        'model_types': ["AutoModelForCausalLM", "AutoModelForSequenceClassification"],
        'cache_dir': "hf_cache",
        'target_type': "embeds",
        'method': "mlm-beamsearch-v0",
       'losses': ["gpt2", "classification_no_prefix_logprobloss"],
       'target_label_ids': [0,0] ,
       'build_loss_dict': {"coeff_steps": 200, "coeff_pattern": "constant", "loss_type": "xentropy", "length_normalize": False, "AR_temperature": 1.0, "AR_top_k": 0, "AR_top_p": 0.96, "max_output_length": 20},
       'min_epsilons': [0.75],
       'source_data': 'new_module/data/toxicity-avoidance/testset_gpt2_2500.jsonl',
       'locate_unit': 'word',
       'locate_method': 'grad_norm',
       'device': 'cuda',
       'k_per_location': 10,
       'closs_weight': 0.9,
       'beam_size': 3}

class dummyArgs:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

build_loss_args = dummyArgs(**config["build_loss_dict"])

In [3]:
name2tokenizer = {}
name2model = {}
name2config = {}
loss2tokenizer = {}
embed_luts = []
primary_model = None
for i, model_path in enumerate(config["model_paths"]):
    if (
        model_path not in name2model
    ):  # making sure we are not loading the model twice in case some constraints use the same model.
        try:
            name2tokenizer[model_path] = AutoTokenizer.from_pretrained(
                config["tokenizer_paths"][i],
                cache_dir=config["cache_dir"],
                use_fast=True,
            )
        except:
            name2tokenizer[model_path] = AutoTokenizer.from_pretrained(
                config["tokenizer_paths"][i],
                cache_dir=config["cache_dir"],
                use_fast=False,
            )

        name2config[model_path] = AutoConfig.from_pretrained(
            model_path, cache_dir=config["cache_dir"]
        )

        if "Custom" in config["model_types"][i]:
            name2model[model_path] = lossbuilder.ModelWrapper(
                getattr(utils, config["model_types"][i]).from_pretrained(
                    model_path,
                    config=name2config[model_path],
                    cache_dir=config["cache_dir"],
                )
            )
        else:
            name2model[model_path] = lossbuilder.ModelWrapper(
                getattr(transformers, config["model_types"][i]).from_pretrained(
                    model_path,
                    config=name2config[model_path],
                    cache_dir=config["cache_dir"],
                )
            )
        name2model[model_path].eval()
        name2model[model_path].cuda()

    input_embeds = name2model[model_path].get_input_embeddings()
    if isinstance(input_embeds, torch.nn.Sequential):
        input_embeds = input_embeds[0]
    embed_luts.append(input_embeds)

    if config["target_type"] == "embeds":
        embed_luts[-1].requires_grad = False

    if i == 0:
        primary_model = name2model[model_path]

mlm_tokenizer = AutoTokenizer.from_pretrained("roberta-base")
mlm = None if config["method"] == "mlm-beamsearch-v2" else AutoModelForMaskedLM.from_pretrained("roberta-base")  

lossfns = []
for i, loss in enumerate(config["losses"]):
    lossfns.append(
        lossbuilder.build_loss(
            loss,
            name2model[config["model_paths"][i]],
            name2tokenizer[config["model_paths"][i]],
            build_loss_args,
        )
    )
    lossfns[i].tokenizer.add_special_tokens({"mask_token": mlm_tokenizer.mask_token})
    loss2tokenizer[loss] = lossfns[i].tokenizer

primary_tokenizer = name2tokenizer['gpt2-large']
secondary_tokenizer = list(name2tokenizer.values())[1]

Starting new HTTPS connection (1): huggingface.co:443
https://huggingface.co:443 "HEAD /gpt2-large/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
https://huggingface.co:443 "HEAD /gpt2-large/resolve/main/config.json HTTP/1.1" 200 0
https://huggingface.co:443 "HEAD /gpt2-large/resolve/main/generation_config.json HTTP/1.1" 200 0
Some weights of the model checkpoint at models/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/checkpoint_best were not used when initializing RobertaForSequenceClassification: ['roberta.embeddings.word_embeddings.0.weight', 'roberta.embeddings.word_embeddings.1.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to

In [4]:
def unravel(outputs_df):
    outputs_df=outputs_df.explode('generations',ignore_index=True)
    outputs_df['prompt']=outputs_df['prompt'].apply(lambda x: x['text'])
    outputs_df['generations']=outputs_df['generations'].apply(lambda x: x['text'] if isinstance(x, dict) else x)
    outputs_df = outputs_df.dropna().reset_index(drop=True)
    return outputs_df
toxic_gen=pd.read_json('new_module/data/toxicity-avoidance/dev_set.jsonl',lines=True)
toxic_gen=unravel(toxic_gen)
prompt = '“I went to use the bathroom, and I went in and Lance was bent'
prediction = toxic_gen.loc[toxic_gen['prompt']==prompt,'generations'].tolist()
ckpt_path = config['model_paths'][1]
model = name2model[ckpt_path] #AutoModelForSequenceClassification.from_pretrained(ckpt_path)
tokenizer = name2tokenizer[ckpt_path] #AutoTokenizer.from_pretrained(ckpt_path)
device='cuda'
model = model.to(device)
loc_machine=LocateMachine(model,tokenizer)
masked_text = loc_machine.locate_main(prediction, "grad_norm", max_num_tokens = 6, unit="word", num_layer=10, label_id=0)

In [5]:
mlm = mlm.to(device)

In [6]:
source_text=prompt

In [7]:
masked_text

["<mask> me<mask><mask><mask><mask><mask> could hear him starting to come, but I didn't stop him. Thank God he had these<mask> on me.",
 ' over like<mask> and he was<mask><mask>',
 ' over me and put his hand in my butt and<mask><mask><mask> his hand up and down my ass and<mask><mask> put his hand back in my butt and<mask> rubbed it.This is',
 '<mask><mask> reaching for his genitals, and so,<mask><mask><mask><mask> the stall door open and I get out," Stephanie<mask><mask>',
 ' over me and he was<mask> me. And I pulled away and he was fighting me, and I<mask><mask><mask><mask><mask> had no idea what<mask> was going<mask>',
 '<mask> the sink. It was dirty. The whole place<mask><mask><mask> the sink and the<mask><mask>',
 ' over the sink and then was bending over one of<mask><mask><mask> and being a<mask><mask> in his pants.',
 '<mask><mask><mask><mask> He just<mask> all this time going<mask> a donkey trying to put a<mask> zippo in.',
 ' over and I flicked my underwear<mask><mask><mask><ma

In [8]:
## replace tokens at the indices with mask tokens
inputs = mlm_tokenizer(
    masked_text, return_tensors="pt", padding=True, truncation=True
)
inputs = inputs.to(device) 

## make predictions for the masked indices
with torch.no_grad():
    logits = mlm(**inputs).logits

special_token_ids = mlm_tokenizer.convert_tokens_to_ids(mlm_tokenizer.all_special_tokens)
logits[:, :, special_token_ids] = -float("inf")

indices_in_mlm_tokens = (
    inputs.input_ids == mlm_tokenizer.mask_token_id
).nonzero(as_tuple=True)

## get top k tokens for each index
predicted_token_ids = torch.topk(
    logits[indices_in_mlm_tokens[0], indices_in_mlm_tokens[1], :],
    k=config['k_per_location'],
    dim=-1,
)
# print(f"predicted_token_ids: {predicted_token_ids}")
# print(f"mlm_tokenizer.batch_decode(predicted_token_ids.indices): {mlm_tokenizer.batch_decode(predicted_token_ids.indices)}")


In [9]:
mlm_tokenizer = AutoTokenizer.from_pretrained("roberta-base")

https://huggingface.co:443 "HEAD /roberta-base/resolve/main/tokenizer_config.json HTTP/1.1" 200 0


In [10]:
inputs = mlm_tokenizer(
    masked_text, return_tensors="pt", padding=True, truncation=True
)
inputs = inputs.to(device) 

In [11]:
input_ids=inputs['input_ids']

In [12]:
edit_indices = sorted(list(set(indices_in_mlm_tokens[1].tolist())))

In [36]:
def beam_rerank(source_text:str, 
                    masked_sequence:torch.Tensor, 
                    indices_in_mlm_tokens:tuple,
                    # predicted_token_ids:torch.return_types.topk,
                    predicted_token_ids:torch.Tensor,
                    mlm_tokenizer:transformers.AutoTokenizer, 
                    lossfns:List[lossbuilder.BaseLoss],
                    config:dict):
    """params: 
    source_text(prompt) should be text. 
    masked_sequence should be token ids tokenized by MLM's tokenizer.
    indices_in_mlm_tokens should be a result of running 
    `indices_in_mlm_tokens = (
                                inputs.input_ids == mlm_tokenizer.mask_token_id
                                ).nonzero(as_tuple=True)`
    """
    
    hypotheses = masked_sequence[:, None, :].repeat((1,config['beam_size'],1))
    edit_indices = sorted(list(set(indices_in_mlm_tokens[1].tolist())))
    print(edit_indices)

    for i in tqdm(edit_indices,total=len(edit_indices)):
        print(i)
        
        batch_ids_to_edit = indices_in_mlm_tokens[0][indices_in_mlm_tokens[1]==i]

        tmp_hypotheses = hypotheses[batch_ids_to_edit].detach().clone()
        tmp_hypotheses=tmp_hypotheses.repeat((1,config['k_per_location'],1))

        # candidates = predicted_token_ids.indices[(indices_in_mlm_tokens[1]==i).nonzero().squeeze(-1),:]
        candidates = predicted_token_ids[(indices_in_mlm_tokens[1]==i).nonzero().squeeze(-1),:]
        candidates = candidates[:, :, None].repeat((1,1, config['beam_size'])).reshape(candidates.shape[0], -1,1)

        tmp_hypotheses = torch.cat((tmp_hypotheses[:, :, :i], candidates),dim=-1) ## tmp_hypotheses: [(a,b,c),(a,b,c), ..., (a,b,c)], candidates: [(p,p,p), (q,q,q), ..., (v,v,v)]
        tmp_hypotheses = tmp_hypotheses.reshape(-1, tmp_hypotheses.shape[-1])
        print(mlm_tokenizer.batch_decode(tmp_hypotheses.reshape(-1, tmp_hypotheses.shape[-1]), skip_special_tokens=True))

        loss_weights = [1 - config['closs_weight'], config['closs_weight']]
        curr_loss = torch.zeros(tmp_hypotheses.shape[0]).to(config['device'])
        for lossid, lossname in enumerate(config["losses"]):
            if config['method'] == 'mlm-beamsearch-v1' and lossid > 0:
                continue
            with torch.no_grad():
                lossvalue = lossfns[lossid].compute_gold_loss(
                    source_text, mlm_tokenizer.batch_decode(tmp_hypotheses,skip_special_tokens=True),
                    label_id=config['target_label_ids'][lossid],
                )
            torch.cuda.empty_cache()
            curr_loss += loss_weights[lossid] * lossvalue
            
        curr_loss = torch.stack(torch.split(curr_loss, config['beam_size'] * config['k_per_location'], dim=0),dim=0)
        top_beams=torch.topk(curr_loss, k=(config['beam_size']*2+1), dim=-1, largest=False).indices

        tmp_hypotheses = torch.split(tmp_hypotheses, config['beam_size'] * config['k_per_location'], dim=0) ## 아래의 작업을 더 간단히 할 수 있는 방법?
        tmp_hypotheses = torch.stack([x[top_beams[j]] for j, x in enumerate(tmp_hypotheses)],dim=0)
        tmp_hypotheses = torch.unique(tmp_hypotheses, dim=1)[:, :config['beam_size'], :]
        print(mlm_tokenizer.batch_decode(tmp_hypotheses.reshape(-1, tmp_hypotheses.shape[-1]), skip_special_tokens=True))

        hypotheses[batch_ids_to_edit,:, i]=tmp_hypotheses[:, :, i]
            
    return mlm_tokenizer.batch_decode(hypotheses.reshape(-1, hypotheses.shape[-1]), skip_special_tokens=True) ## return 값에 대한 의문..!

In [38]:
hypotheses = beam_rerank(source_text, 
                        input_ids, 
                        indices_in_mlm_tokens,
                        predicted_token_ids.indices,
                        mlm_tokenizer, 
                        lossfns,
                        config)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 32, 33]


  0%|          | 0/30 [00:00<?, ?it/s]

1
['Behind', 'Behind', 'Behind', 'Let', 'Let', 'Let', 'With', 'With', 'With', 'Give', 'Give', 'Give', 'Put', 'Put', 'Put', 'Watch', 'Watch', 'Watch', 'Leave', 'Leave', 'Leave', 'Tell', 'Tell', 'Tell', 'For', 'For', 'For', 'To', 'To', 'To', 'I', 'I', 'I', 'He', 'He', 'He', '"', '"', '"', 'She', 'She', 'She', 'We', 'We', 'We', 'They', 'They', 'They', ' "', ' "', ' "', 'Jason', 'Jason', 'Jason', 'Mike', 'Mike', 'Mike', 'Michael', 'Michael', 'Michael', 'And', 'And', 'And', 'Clean', 'Clean', 'Clean', 'Even', 'Even', 'Even', 'But', 'But', 'But', 'In', 'In', 'In', 'See', 'See', 'See', 'Except', 'Except', 'Except', 'Take', 'Take', 'Take', 'Check', 'Check', 'Check', 'Under', 'Under', 'Under', '"', '"', '"', 'He', 'He', 'He', 'I', 'I', 'I', '[', '[', '[', 'H', 'H', 'H', 'The', 'The', 'The', '(', '(', '(', 'And', 'And', 'And', 'Oh', 'Oh', 'Oh', 'D', 'D', 'D', 'The', 'The', 'The', 'A', 'A', 'A', 'This', 'This', 'This', 'D', 'D', 'D', 'C', 'C', 'C', 'R', 'R', 'R', 'B', 'B', 'B', 'H', 'H', 'H', 'P',

  3%|▎         | 1/30 [00:00<00:16,  1.74it/s]

['For', 'Watch', 'Behind', 'I', '"', ' "', 'But', 'In', 'And', '(', '"', '[', 'C', 'H', 'P']
2
['I was', '" was', ' " was', "I's", '"\'s', ' "\'s', "I'm", '"\'m', ' "\'m', 'IHe', '"He', ' "He', 'IStart', '"Start', ' "Start', 'I starts', '" starts', ' " starts', 'I started', '" started', ' " started', 'IStop', '"Stop', ' "Stop', 'II', '"I', ' "I', 'I is', '" is', ' " is', '(,', '",', '[,', "('s", '"\'s', "['s", '(.', '".', '[.', '(:', '":', '[:', '( was', '" was', '[ was', '( is', '" is', '[ is', '( the', '" the', '[ the', '(G', '"G', '[G', '(-', '"-', '[-', '( he', '" he', '[ he', 'C:', 'H:', 'P:', 'C the', 'H the', 'P the', 'C of', 'H of', 'P of', 'C-', 'H-', 'P-', "C's", "H's", "P's", 'CThe', 'HThe', 'PThe', 'C,', 'H,', 'P,', 'C R', 'H R', 'P R', 'C a', 'H a', 'P a', 'C is', 'H is', 'P is']


  7%|▋         | 2/30 [00:00<00:13,  2.06it/s]

[' "I', ' "He', 'I was', '".', '" he', '[,', 'P,', 'C-', 'H,']
3
['For me,', 'Watch me,', 'Behind me,', 'For me in', 'Watch me in', 'Behind me in', 'For me.', 'Watch me.', 'Behind me.', 'For me I', 'Watch me I', 'Behind me I', 'For me and', 'Watch me and', 'Behind me and', 'For me to', 'Watch me to', 'Behind me to', 'For me a', 'Watch me a', 'Behind me a', 'For me on', 'Watch me on', 'Behind me on', 'For me the', 'Watch me the', 'Behind me the', 'For me he', 'Watch me he', 'Behind me he', ' over like him', ' over like him', ' over like him', ' over like that', ' over like that', ' over like that', ' over like it', ' over like it', ' over like it', ' over like,', ' over like,', ' over like,', ' over like this', ' over like this', ' over like this', ' over like me', ' over like me', ' over like me', ' over like you', ' over like you', ' over like you', ' over like everything', ' over like everything', ' over like everything', ' over like something', ' over like something', ' over like so

 10%|█         | 3/30 [00:01<00:13,  1.99it/s]

['For me,', 'For me to', 'Behind me.', ' over like that', ' over like this', ' over like this', '[, yeah', '[, it', '[, right', 'P, a', 'P, the', 'C, and']
4
['For me, the', 'Watch me to the', 'Behind me. the', 'For me, I', 'Watch me to I', 'Behind me. I', 'For me, my', 'Watch me to my', 'Behind me. my', 'For me, he', 'Watch me to he', 'Behind me. he', 'For me, a', 'Watch me to a', 'Behind me. a', 'For me, was', 'Watch me to was', 'Behind me. was', 'For me, his', 'Watch me to his', 'Behind me. his', 'For me, to', 'Watch me to to', 'Behind me. to', 'For me,,', 'Watch me to,', 'Behind me.,', 'For me, and', 'Watch me to and', 'Behind me. and', '(. yeah.', '" he it.', '[, right.', '(. yeah:', '" he it:', '[, right:', '(. yeah?', '" he it?', '[, right?', '(. yeah!', '" he it!', '[, right!', '(. yeah]', '" he it]', '[, right]', '(. yeah."', '" he it."', '[, right."', '(. yeah,', '" he it,', '[, right,', '(. yeah...', '" he it...', '[, right...', '(. yeah)', '" he it)', '[, right)', '(. yeah 

 13%|█▎        | 4/30 [00:02<00:15,  1.66it/s]

['For me, the', 'For me, to', 'For me, and', '[, right.', '(. yeah,', '[, right...', 'P, and and', 'P, and R', 'P, and of']
5
['For me, the door', 'Watch me to to door', 'Behind me. and door', 'For me, the back', 'Watch me to to back', 'Behind me. and back', 'For me, the him', 'Watch me to to him', 'Behind me. and him', 'For me, the.', 'Watch me to to.', 'Behind me. and.', 'For me, the house', 'Watch me to to house', 'Behind me. and house', 'For me, the room', 'Watch me to to room', 'Behind me. and room', 'For me, the,', 'Watch me to to,', 'Behind me. and,', 'For me, the said', 'Watch me to to said', 'Behind me. and said', 'For me, the down', 'Watch me to to down', 'Behind me. and down', 'For me, the me', 'Watch me to to me', 'Behind me. and me', 'C, a and the', 'H- the R the', 'P, and of the', 'C, a and-', 'H- the R-', 'P, and of-', "C, a and's", "H- the R's", "P, and of's", 'C, a and a', 'H- the R a', 'P, and of a', 'C, a and,', 'H- the R,', 'P, and of,', 'C, a and of', 'H- the R of'

 17%|█▋        | 5/30 [00:02<00:15,  1.62it/s]

['For me, the,', 'For me, the back', 'For me, the house', 'C, a and the', 'P, and of a', 'P, and of,']
6
['For me, the,.', 'Watch me to to back.', 'Behind me. and house.', 'For me, the,,', 'Watch me to to back,', 'Behind me. and house,', 'For me, the, and', 'Watch me to to back and', 'Behind me. and house and', 'For me, the,!', 'Watch me to to back!', 'Behind me. and house!', 'For me, the,?', 'Watch me to to back?', 'Behind me. and house?', 'For me, the, where', 'Watch me to to back where', 'Behind me. and house where', 'For me, the, said', 'Watch me to to back said', 'Behind me. and house said', 'For me, the, because', 'Watch me to to back because', 'Behind me. and house because', 'For me, the, that', 'Watch me to to back that', 'Behind me. and house that', 'For me, the, I', 'Watch me to to back I', 'Behind me. and house I', ' over me and he was choking', ' over me and he was choking', ' over me and he was choking', ' over me and he was fighting', ' over me and he was fighting', ' ove

 20%|██        | 6/30 [00:03<00:13,  1.74it/s]

['For me, the,,', 'For me, the, and', 'For me, the, that', ' over me and he was pushing', ' over me and he was choking', ' over me and he was choking', 'C, a and the and', 'P, and of, the', 'P, and of, a']
7
['For me, the,, I', 'Watch me to to back and I', 'Behind me. and house that I', 'For me, the,,I', 'Watch me to to back andI', 'Behind me. and house thatI', 'For me, the,, You', 'Watch me to to back and You', 'Behind me. and house that You', 'For me, the,, you', 'Watch me to to back and you', 'Behind me. and house that you', 'For me, the,, and', 'Watch me to to back and and', 'Behind me. and house that and', 'For me, the,, We', 'Watch me to to back and We', 'Behind me. and house that We', 'For me, the,, He', 'Watch me to to back and He', 'Behind me. and house that He', 'For me, the,,You', 'Watch me to to back andYou', 'Behind me. and house thatYou', 'For me, the,, we', 'Watch me to to back and we', 'Behind me. and house that we', 'For me, the,, he', 'Watch me to to back and he', 'Be

 23%|██▎       | 7/30 [00:03<00:12,  1.80it/s]

['For me, the,, and', 'For me, the,, he', 'For me, the,, I', ' over like this and he was like', ' over like that and he was like', ' over like this and he was like', '[, right... He just had', '(. yeah. He just took', '(. yeah. He just had']
8
[' over like that and he was like.', ' over like this and he was like.', ' over like this and he was like.', ' over like that and he was like!', ' over like this and he was like!', ' over like this and he was like!', ' over like that and he was like:', ' over like this and he was like:', ' over like this and he was like:', ' over like that and he was like?', ' over like this and he was like?', ' over like this and he was like?', ' over like that and he was like…', ' over like this and he was like…', ' over like this and he was like…', ' over like that and he was like...', ' over like this and he was like...', ' over like this and he was like...', ' over like that and he was like …', ' over like this and he was like …', ' over like this and he was

 27%|██▋       | 8/30 [00:04<00:10,  2.06it/s]

[' over like that and he was like:', ' over like this and he was like:', ' over like this and he was like...', ' over and I flicked my underwear up', ' over and I flicked my underwear off', ' over and I flicked my underwear at']
9
[' over and I flicked my underwear up,', ' over and I flicked my underwear off,', ' over and I flicked my underwear at,', ' over and I flicked my underwear up the', ' over and I flicked my underwear off the', ' over and I flicked my underwear at the', ' over and I flicked my underwear up a', ' over and I flicked my underwear off a', ' over and I flicked my underwear at a', ' over and I flicked my underwear up and', ' over and I flicked my underwear off and', ' over and I flicked my underwear at and', ' over and I flicked my underwear up to', ' over and I flicked my underwear off to', ' over and I flicked my underwear at to', ' over and I flicked my underwear up at', ' over and I flicked my underwear off at', ' over and I flicked my underwear at at', ' over an

 30%|███       | 9/30 [00:04<00:09,  2.28it/s]

[' over and I flicked my underwear up,', ' over and I flicked my underwear up to', ' over and I flicked my underwear up and', 'P, and of, a master bike when', 'C, a and the and master bike was', 'P, and of, a master bike was']
10
[' over and I flicked my underwear up, the', ' over and I flicked my underwear off to the', ' over and I flicked my underwear at and the', ' over and I flicked my underwear up, a', ' over and I flicked my underwear off to a', ' over and I flicked my underwear at and a', ' over and I flicked my underwear up,,', ' over and I flicked my underwear off to,', ' over and I flicked my underwear at and,', ' over and I flicked my underwear up, same', ' over and I flicked my underwear off to same', ' over and I flicked my underwear at and same', ' over and I flicked my underwear up, to', ' over and I flicked my underwear off to to', ' over and I flicked my underwear at and to', ' over and I flicked my underwear up, at', ' over and I flicked my underwear off to at', ' ove

 33%|███▎      | 10/30 [00:04<00:07,  2.69it/s]

[' over and I flicked my underwear up, the', ' over and I flicked my underwear up, to', ' over and I flicked my underwear up, a']
11
[' over me and put his hand in my butt and he', ' over me and put his hand in my butt and he', ' over me and put his hand in my butt and he', ' over me and put his hand in my butt and then', ' over me and put his hand in my butt and then', ' over me and put his hand in my butt and then', ' over me and put his hand in my butt and kind', ' over me and put his hand in my butt and kind', ' over me and put his hand in my butt and kind', ' over me and put his hand in my butt and and', ' over me and put his hand in my butt and and', ' over me and put his hand in my butt and and', ' over me and put his hand in my butt and so', ' over me and put his hand in my butt and so', ' over me and put his hand in my butt and so', ' over me and put his hand in my butt and just', ' over me and put his hand in my butt and just', ' over me and put his hand in my butt and just',

 37%|███▋      | 11/30 [00:05<00:09,  2.10it/s]

[' over me and put his hand in my butt and he', ' over me and put his hand in my butt and he', ' over me and put his hand in my butt and he', 'II reaching for his genitals, and so, and', 'II reaching for his genitals, and so, he', 'II reaching for his genitals, and so, I', ' over the sink and then was bending over one of the', ' over the sink and then was bending over one of the', ' over the sink and then was bending over one of the', ' over and I flicked my underwear off to to the', ' over and I flicked my underwear up, the same', ' over and I flicked my underwear up, the one', 'P, and of, a master bike was seen riding', 'P, and of, a master bike was seen on', 'P, and of, a master bike was seen in']
12
[' over me and put his hand in my butt and he he', ' over me and put his hand in my butt and he he', ' over me and put his hand in my butt and he he', ' over me and put his hand in my butt and he started', ' over me and put his hand in my butt and he started', ' over me and put his hand

 40%|████      | 12/30 [00:06<00:10,  1.66it/s]

[' over me and put his hand in my butt and he was', ' over me and put his hand in my butt and he was', ' over me and put his hand in my butt and he was', 'II reaching for his genitals, and so, and,', 'II reaching for his genitals, and so, and I', 'II reaching for his genitals, and so, and just', 'In the sink. It was dirty. The whole place smelled', 'In the sink. It was dirty. The whole place was', 'In the sink. It was dirty. The whole place.', ' over the sink and then was bending over one of the toilet', ' over the sink and then was bending over one of the toilet', ' over the sink and then was bending over one of the toilet', '[, right... He just had all this time going through', '[, right... He just had all this time going to', '[, right... He just had all this time going over', 'P, and of, a master bike was seen in a', 'P, and of, a master bike was seen in the', 'P, and of, a master bike was seen in this']
13
[' over me and put his hand in my butt and he was rubbed', ' over me and pu

 43%|████▎     | 13/30 [00:07<00:11,  1.50it/s]

[' over me and put his hand in my butt and he was running', ' over me and put his hand in my butt and he was moving', ' over me and put his hand in my butt and he was moving', 'II reaching for his genitals, and so, and, just', ' " was reaching for his genitals, and so, I just,', 'II reaching for his genitals, and so, and,,', 'In the sink. It was dirty. The whole place was up', 'In the sink. It was dirty. The whole place was,', 'In the sink. It was dirty. The whole place was dirt', ' over the sink and then was bending over one of the toilet cabinets', ' over the sink and then was bending over one of the toilet sinks', ' over the sink and then was bending over one of the toilet sinks', 'P, and of, a master bike was seen in this of', 'P, and of, a master bike was seen in this-', 'P, and of, a master bike was seen in this a']
14
['II reaching for his genitals, and so, and, just get', '"He reaching for his genitals, and so, he I, get', ' " was reaching for his genitals, and so, I just, get'

 47%|████▋     | 14/30 [00:07<00:09,  1.60it/s]

[' " was reaching for his genitals, and so, I just, get', ' " was reaching for his genitals, and so, I just, got', ' " was reaching for his genitals, and so, I just, hold', 'In the sink. It was dirty. The whole place was, just', 'In the sink. It was dirty. The whole place was, but', 'In the sink. It was dirty. The whole place was, except', 'P, and of, a master bike was seen in this a.', 'P, and of, a master bike was seen in this a,', 'P, and of, a master bike was seen in this a and']
15
['C, a and the and master bike when seen riding a of. in', 'H- the R a the master bike was seen on the-, in', 'P, and of, a master bike was seen in this a and in', 'C, a and the and master bike when seen riding a of.,', 'H- the R a the master bike was seen on the-,,', 'P, and of, a master bike was seen in this a and,', 'C, a and the and master bike when seen riding a of. the', 'H- the R a the master bike was seen on the-, the', 'P, and of, a master bike was seen in this a and the', 'C, a and the and mas

 50%|█████     | 15/30 [00:07<00:07,  1.99it/s]

['P, and of, a master bike was seen in this a and.', 'P, and of, a master bike was seen in this a and the', 'P, and of, a master bike was seen in this a and,']
16
['C, a and the and master bike when seen riding a of..,', 'H- the R a the master bike was seen on the-, the,', 'P, and of, a master bike was seen in this a and,,', 'C, a and the and master bike when seen riding a of.. in', 'H- the R a the master bike was seen on the-, the in', 'P, and of, a master bike was seen in this a and, in', 'C, a and the and master bike when seen riding a of...', 'H- the R a the master bike was seen on the-, the.', 'P, and of, a master bike was seen in this a and,.', 'C, a and the and master bike when seen riding a of.. the', 'H- the R a the master bike was seen on the-, the the', 'P, and of, a master bike was seen in this a and, the', 'C, a and the and master bike when seen riding a of.. of', 'H- the R a the master bike was seen on the-, the of', 'P, and of, a master bike was seen in this a and, of', 

 53%|█████▎    | 16/30 [00:08<00:05,  2.41it/s]

['P, and of, a master bike was seen in this a and, the', 'P, and of, a master bike was seen in this a and,,', 'P, and of, a master bike was seen in this a and, and']
17
[' over the sink and then was bending over one of the toilet cabinets and being a little', ' over the sink and then was bending over one of the toilet sinks and being a little', ' over the sink and then was bending over one of the toilet sinks and being a little', ' over the sink and then was bending over one of the toilet cabinets and being a bit', ' over the sink and then was bending over one of the toilet sinks and being a bit', ' over the sink and then was bending over one of the toilet sinks and being a bit', ' over the sink and then was bending over one of the toilet cabinets and being a big', ' over the sink and then was bending over one of the toilet sinks and being a big', ' over the sink and then was bending over one of the toilet sinks and being a big', ' over the sink and then was bending over one of the toi

 57%|█████▋    | 17/30 [00:08<00:05,  2.48it/s]

[' over the sink and then was bending over one of the toilet sinks and being a good', ' over the sink and then was bending over one of the toilet sinks and being a big', ' over the sink and then was bending over one of the toilet sinks and being a big', 'P, and of, a master bike was seen in this a and, and-', 'P, and of, a master bike was seen in this a and, and and', 'P, and of, a master bike was seen in this a and, and in']
18
[' over the sink and then was bending over one of the toilet cabinets and being a good man', ' over the sink and then was bending over one of the toilet sinks and being a big man', ' over the sink and then was bending over one of the toilet sinks and being a big man', ' over the sink and then was bending over one of the toilet cabinets and being a good boy', ' over the sink and then was bending over one of the toilet sinks and being a big boy', ' over the sink and then was bending over one of the toilet sinks and being a big boy', ' over the sink and then was b

 60%|██████    | 18/30 [00:09<00:05,  2.39it/s]

[' over the sink and then was bending over one of the toilet cabinets and being a good boy', ' over the sink and then was bending over one of the toilet sinks and being a big boy', ' over the sink and then was bending over one of the toilet sinks and being a big boy', 'P, and of, a master bike was seen in this a and, and in).', 'P, and of, a master bike was seen in this a and, and in:', 'P, and of, a master bike was seen in this a and, and in!']
19
['But the sink. It was dirty. The whole place smelled up just the sink and the toilet', 'In the sink. It was dirty. The whole place was, but the sink and the toilet', 'And the sink. It was dirty. The whole place. dirt except the sink and the toilet', 'But the sink. It was dirty. The whole place smelled up just the sink and the floor', 'In the sink. It was dirty. The whole place was, but the sink and the floor', 'And the sink. It was dirty. The whole place. dirt except the sink and the floor', 'But the sink. It was dirty. The whole place smel

 63%|██████▎   | 19/30 [00:09<00:04,  2.33it/s]

['In the sink. It was dirty. The whole place was, but the sink and the water', 'In the sink. It was dirty. The whole place was, but the sink and the floor', 'In the sink. It was dirty. The whole place was, but the sink and the counter', '[, right... He just had all this time going over a donkey trying to put a new', '(. yeah. He just had all this time going through a donkey trying to put a fucking', '[, right... He just had all this time going over a donkey trying to put a fucking']
20
['But the sink. It was dirty. The whole place smelled up just the sink and the water.', 'In the sink. It was dirty. The whole place was, but the sink and the floor.', 'And the sink. It was dirty. The whole place. dirt except the sink and the counter.', 'But the sink. It was dirty. The whole place smelled up just the sink and the water!', 'In the sink. It was dirty. The whole place was, but the sink and the floor!', 'And the sink. It was dirty. The whole place. dirt except the sink and the counter!', 'But

 67%|██████▋   | 20/30 [00:09<00:03,  2.61it/s]

['In the sink. It was dirty. The whole place was, but the sink and the floor.', 'In the sink. It was dirty. The whole place was, but the sink and the floor,', 'In the sink. It was dirty. The whole place was, but the sink and the floor?']
21
[' over me and he was pushing me. And I pulled away and he was fighting me, and I was', ' over me and he was choking me. And I pulled away and he was fighting me, and I was', ' over me and he was choking me. And I pulled away and he was fighting me, and I was', ' over me and he was pushing me. And I pulled away and he was fighting me, and I just', ' over me and he was choking me. And I pulled away and he was fighting me, and I just', ' over me and he was choking me. And I pulled away and he was fighting me, and I just', ' over me and he was pushing me. And I pulled away and he was fighting me, and I had', ' over me and he was choking me. And I pulled away and he was fighting me, and I had', ' over me and he was choking me. And I pulled away and he w

 70%|███████   | 21/30 [00:10<00:03,  2.85it/s]

[' over me and he was choking me. And I pulled away and he was fighting me, and I was', ' over me and he was choking me. And I pulled away and he was fighting me, and I just', ' over me and he was choking me. And I pulled away and he was fighting me, and I got']
22
[' over me and put his hand in my butt and he was running his hand up and down my ass and then', ' over me and put his hand in my butt and he was moving his hand up and down my ass and then', ' over me and put his hand in my butt and he was moving his hand up and down my ass and then', ' over me and put his hand in my butt and he was running his hand up and down my ass and he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he', ' over me and put his hand in my butt and he was running his hand up and down my ass and I', ' over me and put his hand in my butt and he was moving his hand up and do

 73%|███████▎  | 22/30 [00:10<00:03,  2.62it/s]

[' over me and put his hand in my butt and he was running his hand up and down my ass and he', ' over me and put his hand in my butt and he was running his hand up and down my ass and I', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he', ' over me and he was choking me. And I pulled away and he was fighting me, and I got to', ' over me and he was choking me. And I pulled away and he was fighting me, and I got in', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was just']
23
[' over me and put his hand in my butt and he was running his hand up and down my ass and he he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and I he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he he', ' over me and put his hand in my butt and he was running his hand up and down my ass and he and', ' over me and put his hand in my butt and he was moving h

 77%|███████▋  | 23/30 [00:10<00:02,  2.46it/s]

[' over me and put his hand in my butt and he was running his hand up and down my ass and he just', ' over me and put his hand in my butt and he was running his hand up and down my ass and he then', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he also', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in,', ' over me and he was choking me. And I pulled away and he was fighting me, and I got just up', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in and']
24
[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in up and', ' over me and he was choking me. And I pulled away and he was fighting me, and I got just and and', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to,.', ' over me and he was choking me.

 80%|████████  | 24/30 [00:11<00:02,  2.71it/s]

[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, I', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, like']
25
['II reaching for his genitals, and so, and, just get the stall door open and I get out," Stephanie said', '"He reaching for his genitals, and so, he I, got the stall door open and I get out," Stephanie said', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie said', 'II reaching for his genitals, and so, and, just get the stall door open and I get out," Stephanie says', '"He reaching for his genitals, and so, he I, got the stall door open and I get out," Stephanie says', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie says', 'II reaching for his genitals, and so, and, just get the stall door open an

 83%|████████▎ | 25/30 [00:11<00:02,  2.47it/s]

[' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie said', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie says', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie explained', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and he', ' over me and he was choking me. And I pulled away and he was fighting me, and I got just and like,']
26
['II reaching for his genitals, and so, and, just get the stall door open and I get out," Stephanie said.', '"He reaching for his genitals, and so, he I, got the stall door open and I get out," Stephanie says.', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie explained.', 'II reaching for his genitals, and so, a

 87%|████████▋ | 26/30 [00:12<00:01,  2.68it/s]

[' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie explained.', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie explained,', ' " was reaching for his genitals, and so, I just, hold the stall door open and I get out," Stephanie explained of']
27
["For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these handcuffs", "Watch me to to back and he could hear him starting to come, but I didn't stop him. Thank God he had these handcuffs", "Behind me. and house that I could hear him starting to come, but I didn't stop him. Thank God he had these handcuffs", "For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these clothes", "Watch me to to back and he could hear him starting to come, but I didn't stop him. Thank God he had these clothes", "Behind me. and house that I could hear him starting to come, but I didn't

 90%|█████████ | 27/30 [00:12<00:01,  2.84it/s]

["For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these things", "For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these clothes", "For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these shoes"]
30
[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what I', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in up I he had no idea what I', ' over me and he was choking me. And I pulled away and he was fighting me, and I got just and like, had no idea what I', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what he', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in up I he had no idea what he', ' over me and he was choking me. And I pulled away and he was fighting me, and I go

 93%|█████████▎| 28/30 [00:12<00:00,  2.95it/s]

[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what it', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what he']
32
[' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and I then put his hand back in my butt and he', ' over me and put his hand in my butt and he was moving his hand up and down my ass and he also put his hand back in my butt and he', ' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and just', ' over me and put his hand in my butt and he was moving his hand up and down my ass and I then put his 

 97%|█████████▋| 29/30 [00:12<00:00,  2.91it/s]

[' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and he', ' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and I', ' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and just']
33
[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that was going.', ' over me and he was choking me. And I pulled away and he was fighting me, and I just in up I he had no idea what it was going.', ' over me and he was choking me. And I pulled away and he was fighting me, and I got just and like, had no idea what he was going.', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that was going on', ' over me and he was choking me. And I pulled away and he was fi

100%|██████████| 30/30 [00:13<00:00,  2.25it/s]

[' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that was going to', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that was going on', ' over me and he was pushing me. And I pulled away and he was fighting me, and I was to, and I had no idea what that was going through']


In [44]:
input_ids[[1],:].shape

torch.Size([1, 39])

In [32]:
indices_in_mlm_tokens_subset = (torch.zeros_like(indices_in_mlm_tokens[1][indices_in_mlm_tokens[0]==1]),
                                indices_in_mlm_tokens[1][indices_in_mlm_tokens[0]==1]) 

In [33]:
edit_indices = sorted(list(set(indices_in_mlm_tokens_subset[1].tolist())))

In [17]:
edit_indices

[3, 7, 8]

In [34]:
predicted_token_ids_subset = predicted_token_ids.indices[indices_in_mlm_tokens[0]==1]

In [61]:
predicted_token_ids_subset.shape

torch.Size([2, 10])

In [22]:
indices_in_mlm_tokens_subset[1]

tensor([3, 7, 8], device='cuda:0')

In [29]:
indices_in_mlm_tokens_subset[0]

tensor([0, 0, 0], device='cuda:0')

In [30]:
indices_in_mlm_tokens_subset[0][indices_in_mlm_tokens_subset[1]==3]

tensor([0], device='cuda:0')

In [37]:
hypotheses_subset = beam_rerank(source_text, 
                        input_ids[[1],:], 
                        indices_in_mlm_tokens_subset,
                        predicted_token_ids_subset,
                        mlm_tokenizer, 
                        lossfns,
                        config)

[3, 7, 8]


 33%|███▎      | 1/3 [00:00<00:00,  6.87it/s]

3
[' over like him', ' over like him', ' over like him', ' over like that', ' over like that', ' over like that', ' over like it', ' over like it', ' over like it', ' over like,', ' over like,', ' over like,', ' over like this', ' over like this', ' over like this', ' over like me', ' over like me', ' over like me', ' over like you', ' over like you', ' over like you', ' over like everything', ' over like everything', ' over like everything', ' over like something', ' over like something', ' over like something', ' over like them', ' over like them', ' over like them']
[' over like,', ' over like that', ' over like this']
7
[' over like, and he was like', ' over like that and he was like', ' over like this and he was like', ' over like, and he was so', ' over like that and he was so', ' over like this and he was so', ' over like, and he was really', ' over like that and he was really', ' over like this and he was really', ' over like, and he was cool', ' over like that and he was cool'

100%|██████████| 3/3 [00:00<00:00,  6.41it/s]

[' over like, and he was like', ' over like that and he was so', ' over like that and he was like']
8
[' over like, and he was like.', ' over like that and he was so.', ' over like this and he was like.', ' over like, and he was like!', ' over like that and he was so!', ' over like this and he was like!', ' over like, and he was like:', ' over like that and he was so:', ' over like this and he was like:', ' over like, and he was like?', ' over like that and he was so?', ' over like this and he was like?', ' over like, and he was like…', ' over like that and he was so…', ' over like this and he was like…', ' over like, and he was like...', ' over like that and he was so...', ' over like this and he was like...', ' over like, and he was like …', ' over like that and he was so …', ' over like this and he was like …', ' over like, and he was like."', ' over like that and he was so."', ' over like this and he was like."', ' over like, and he was like me', ' over like that and he was so me',

In [47]:
indices_in_mlm_tokens[1][indices_in_mlm_tokens[0]==1]

tensor([3, 5], device='cuda:0')

In [50]:
mlm_tokenizer.decode(input_ids[1,])

'<s> over like<mask> and<mask> was f...</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>'

In [53]:
predicted_token_ids.indices[indices_in_mlm_tokens[0]==1]

tensor([[   14,    42,     6,   162,    24, 15328,   123,  7105,  1085,  2350],
        [   38,    24,    37,    14,    79,   960,    42,    89,   961,   172]],
       device='cuda:0')

In [25]:
hypotheses1 = hypotheses.detach().clone()

In [31]:
hypotheses1[hypotheses1 != hypotheses]

tensor([   24,    11,    10,    15,    37,    39,    62, 32651,    31,   514,
          133,    56,   514,     6,    24,  7516,    95,    11,  1929,   514,
           37,    21,   169,     6,   172,     6,   734,     7,    37,     8,
        38821,     4, 14292,    17,     5,     4,    17, 48584,     7,     6,
            6,     6,     6, 14292,  1174, 10278,    35,    12, 48584,   133,
            4,     8,     4], device='cuda:0')

In [32]:
hypotheses[hypotheses1 != hypotheses]

tensor([   37,    15,   127,    11,    10,    10,    15,     4,     7,    72,
         7516,  1415, 35200,    19,   514,   133, 35200,    31, 11471,  1929,
          172,     6, 20745,     4,    37,    21,     6,     5,   172,     6,
          652,     6, 10278,     5,    10,    35,    35,   176,   134,     5,
            5,    35,    12,     8,   328, 14292,   176,     6,   176,     6,
           19,    12,   467], device='cuda:0')

In [40]:
hypotheses

["For me, the,, and could hear him starting to come, but I didn't stop him. Thank God he had these things on me.",
 "Watch me to to back and he could hear him starting to come, but I didn't stop him. Thank God he had these clothes on me.",
 "Behind me. and house that I could hear him starting to come, but I didn't stop him. Thank God he had these shoes on me.",
 ' over like that and he was like:',
 ' over like this and he was like:',
 ' over like this and he was like...',
 ' over me and put his hand in my butt and he was running his hand up and down my ass and he just put his hand back in my butt and he rubbed it.This is',
 ' over me and put his hand in my butt and he was moving his hand up and down my ass and I then put his hand back in my butt and I rubbed it.This is',
 ' over me and put his hand in my butt and he was moving his hand up and down my ass and he also put his hand back in my butt and just rubbed it.This is',
 'II reaching for his genitals, and so, and, just get the stall

In [39]:
mlm_tokenizer.batch_decode(hypotheses.reshape(-1, hypotheses.shape[-1]), skip_special_tokens=True)

AttributeError: 'list' object has no attribute 'reshape'

In [18]:
mlm_tokenizer.batch_decode(hypotheses.reshape(-1, hypotheses.shape[-1]), skip_special_tokens=True)

[" over me trying to cum. I could see he was to the, but I didn't stop him. And God he had these pants on me.",
 " over me trying to cum. I could tell his was of to out but I didn't stop him. By God he had these pants on me.",
 " over me trying to cum. I could tell him cock in it off but I didn't stop him. My God he had these pants on me.",
 ' over like, and it was f...',
 ' over like, and he was f...',
 ' over like, and he was f...',
 'led me and put the hand in my butt and he hand forced his way up and down my ass and then he put his hand back in my face and he rubbed it.This is',
 'handed me and put a hand on my butt and he hand forced his head up and down my ass and then he put his hand back in my hand and he rubbed it.This is',
 'behind me and put his hand up my butt and his hand forced his hand up and down my ass and then he put his hand back in my ass and he rubbed it.This is',
 ' over, reaching for his genitals, and so, he just jerked the stall door open and took the door. Step

In [60]:
top_beams

tensor([[11, 10,  9],
        [ 2,  1,  0]], device='cuda:0')

In [24]:
tmp_hypotheses.shape

torch.Size([8, 30, 39])

In [25]:
hypotheses.shape

torch.Size([10, 3, 39])

In [27]:
i=1

In [37]:
expanded_tmp_hypotheses.reshape(-1, expanded_tmp_hypotheses.shape[-1]).shape

torch.Size([240, 39])

In [35]:
tmp_hypotheses.shape

torch.Size([240, 2])

In [11]:
predicted_token_ids.indices.shape

torch.Size([68, 10])

In [13]:
indices_in_mlm_tokens

(tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4,
         4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7,
         7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        device='cuda:0'),
 tensor([ 1,  2, 10, 11, 28, 29, 30,  1,  2,  1, 11, 12, 29, 30, 32,  1,  2, 11,
         12, 21, 22, 23, 21, 29, 30, 31, 32, 33,  1,  2, 11, 12, 13, 14,  1,  9,
         11, 12, 13, 21, 22,  1,  2,  8,  9, 10, 20, 21, 22,  1, 12, 13, 20, 21,
          1,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16],
        device='cuda:0'))

In [124]:
## 일단 무조건 한 스텝 extend하고, 그 다음에 extend한 곳의 값들을 수정하는 방식으로 해보는건 어떨까? 
hypotheses = torch.cat([hypotheses, masked_sequence[:, None, i].unsqueeze(1).expand(-1, config['beam_size'], 1)],dim=-1)

In [126]:
skipping_batch_ids = (masked_sequence[:, i] == mlm_tokenizer.mask_token_id).nonzero()

In [127]:
skipping_batch_ids ## for loop over these indices?

tensor([[0],
        [1],
        [2],
        [3],
        [5],
        [6],
        [7],
        [8],
        [9]], device='cuda:0')

In [61]:
hypotheses[skipping_batch_ids.squeeze()]

tensor([], device='cuda:0', size=(10, 3, 0), dtype=torch.int64)

In [63]:
masked_sequence[skipping_batch_ids.squeeze(), i]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')

In [70]:
masked_sequence[skipping_batch_ids.squeeze(), i].unsqueeze(1).unsqueeze(1).expand(len(skipping_batch_ids), config['beam_size'], 1).shape

torch.Size([10, 3, 1])

In [41]:
masked_sequence[skipping_batch_ids, i].shape

torch.Size([1, 1])

In [ ]:
hypotheses = [torch.LongTensor([]).to(config['device'])]
L = masked_sequence.size(-1)
for i in range(L):
    

In [14]:
hypotheses = [torch.LongTensor([]).to(config['device'])]
L = masked_sequence.size(-1)

for i in range(L):
    if masked_sequence[:, i] != mlm_tokenizer.mask_token_id:
        hypotheses = list(torch.cat([torch.stack(hypotheses,dim=0), 
                                    masked_sequence[:, i].unsqueeze(0).repeat((len(hypotheses),1)).to(config['device'])],dim=-1))
    else:
        num_hypotheses = len(hypotheses)
        hypotheses = torch.stack(hypotheses,dim=0).unsqueeze(0)
        hypotheses = hypotheses.repeat(config['k_per_location'], 1, 1)
        candidates = predicted_token_ids.indices[torch.where(indices_in_mlm_tokens == i)[0], :].to(config['device']).T.unsqueeze(1) ## 이부분이 바뀌어야 함
        candidates = candidates.repeat(1, num_hypotheses, 1)
        hypotheses_exp = torch.cat([hypotheses, candidates], dim=-1)
        hypotheses_exp = hypotheses_exp.view(-1, hypotheses_exp.shape[-1])
        hypotheses_exp = list(hypotheses_exp)

        losses = []
        loss_weights = [1 - config['closs_weight'], config['closs_weight']]
        for hyp in hypotheses_exp:
            curr_loss = 0.0
            for lossid, lossname in enumerate(config["losses"]):
                with torch.no_grad():
                    lossvalue = lossfns[lossid].compute_gold_loss(
                        source_text, mlm_tokenizer.decode(hyp, skip_special_tokens=True),
                        label_id=config['target_label_ids'][lossid],
                    )
                curr_loss += loss_weights[lossid] * lossvalue.item()
            losses.append(curr_loss)

        hypotheses = sorted(zip(hypotheses_exp, losses), key=lambda x: x[1])[:config['beam_size']]
        hypotheses = [x[0] for x in hypotheses]

TypeError: where(): argument 'condition' (position 1) must be Tensor, not bool

In [ ]:

def beam_rerank_v0(source_text, ## text (too arbitrary?)
                    masked_sequence, ## in mlm tokenizer's tokens
                    indices_in_mlm_tokens,
                    predicted_token_ids,
                    mlm_tokenizer, 
                    lossfns,
                    config, 
                    beam_size = 5):
    
    hypotheses = [torch.LongTensor([]).to(config['device'])]
    L = masked_sequence.size(-1)

    for i in range(L):
        if masked_sequence[0, i] != mlm_tokenizer.mask_token_id:
            hypotheses = list(torch.cat([torch.stack(hypotheses,dim=0), 
                                        masked_sequence[:, i].unsqueeze(0).repeat((len(hypotheses),1)).to(config['device'])],dim=-1))
        else:
            num_hypotheses = len(hypotheses)
            hypotheses = torch.stack(hypotheses,dim=0).unsqueeze(0)
            hypotheses = hypotheses.repeat(config['k_per_location'], 1, 1)
            candidates = predicted_token_ids.indices[torch.where(indices_in_mlm_tokens == i)[0], :].to(config['device']).T.unsqueeze(1)
            candidates = candidates.repeat(1, num_hypotheses, 1)
            hypotheses_exp = torch.cat([hypotheses, candidates], dim=-1)
            hypotheses_exp = hypotheses_exp.view(-1, hypotheses_exp.shape[-1])
            hypotheses_exp = list(hypotheses_exp)

            losses = []
            loss_weights = [1 - wandb.config.closs_weight, wandb.config.closs_weight]
            for hyp in hypotheses_exp:
                curr_loss = 0.0
                for lossid, lossname in enumerate(config["losses"]):
                    with torch.no_grad():
                        lossvalue = lossfns[lossid].compute_gold_loss(
                            source_text, mlm_tokenizer.decode(hyp, skip_special_tokens=True),
                            label_id=config['target_label_ids'][lossid],
                        )
                    curr_loss += loss_weights[lossid] * lossvalue.item()
                losses.append(curr_loss)

            hypotheses = sorted(zip(hypotheses_exp, losses), key=lambda x: x[1])[:beam_size]
            hypotheses = [x[0] for x in hypotheses]
            
    return [mlm_tokenizer.decode(x, skip_special_tokens=True) for x in hypotheses]
